name: QA Pipeline

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  api-tests:
    name: API Tests (Newman)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run ./newman/RestfulBooker.postman_collection.json \
            -e ./newman/restful_booker.postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export reports/api-report.xml

      - name: Upload API Report
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: reports/api-report.xml

  ui-tests:
    name: UI Tests (Playwright + Cucumber)
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: drvn-challenge/pw
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: drvn-challenge/pw
        run: npx playwright install --with-deps

      - name: Run UI Tests
        working-directory: drvn-challenge/pw
        run: npm run test:report

      - name: Upload UI Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-artifacts
          path: |
            drvn-challenge/pw/reports/
            drvn-challenge/pw/test-results/
            drvn-challenge/pw/playwright-report/